setwd("D:/research/populus-simonii/LV/program")
library(deSolve)
library(mvtnorm)
library(ggplot2)
library(grid)
library(lars)
library(igraph)
load("renewgen.Rdata")
load("renewsnpinfo.Rdata")
load("expheno.Rdata")
load("lvretnew.Rdata")
load("intercross.Rdata")
load("testcross.Rdata")
load("map.Rdata")
source("renewode.R")
source("lvcovar.R")
source("lvcurve.R")
source("lvoptim.R")
source("lvplot.R")
source("lvsimu.R")
source("lvsimuoptim.R")
light1<-colMeans(expheno[,1:11])
light2<-log(colMeans(expheno[,1:11]))
ret<-lvretnew



